Changes that makes branch pytorch, scheduler, standart theme

diff --git a/configs/Dockerfile.ipex b/configs/Dockerfile.ipex
--- a/configs/Dockerfile.ipex
+++ b/configs/Dockerfile.ipex
@@ -6,17 +6,17 @@ FROM ubuntu:noble
 
 # metadata
 LABEL org.opencontainers.image.vendor="SD.Next"
-LABEL org.opencontainers.image.authors="disty0"
-LABEL org.opencontainers.image.url="https://github.com/vladmandic/sdnext/"
+LABEL org.opencontainers.image.authors="liutyi"
+LABEL org.opencontainers.image.url="https://github.com/liutyi/sdnext"
 LABEL org.opencontainers.image.documentation="https://github.com/vladmandic/sdnext/wiki/Docker"
 LABEL org.opencontainers.image.source="https://github.com/vladmandic/sdnext/"
 LABEL org.opencontainers.image.licenses="AGPL-3.0"
-LABEL org.opencontainers.image.title="SD.Next IPEX"
+LABEL org.opencontainers.image.title="SD.Next IPEX for Intel Arc"
 LABEL org.opencontainers.image.description="SD.Next: Advanced Implementation of Stable Diffusion and other Diffusion-based generative image models"
 LABEL org.opencontainers.image.base.name="https://hub.docker.com/_/ubuntu:noble"
-LABEL org.opencontainers.image.version="latest"
+LABEL org.opencontainers.image.version="25.12-pytorch"
 
-# essentials
+# essentials and required by pytorch / ipex
 RUN apt-get update && \
     apt-get install -y --no-install-recommends --fix-missing \
     software-properties-common \
@@ -24,23 +24,17 @@ RUN apt-get update && \
     ca-certificates \
     wget \
     gpg \
-    git
-
-# intel compute runtime
-RUN wget -qO - https://repositories.intel.com/gpu/intel-graphics.key | gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg
-RUN echo "deb [arch=amd64,i386 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu noble client" | tee /etc/apt/sources.list.d/intel-gpu-noble.list
-RUN apt-get update
-
-RUN apt-get install -y --no-install-recommends --fix-missing \
-    intel-opencl-icd \
-    libze-intel-gpu1 \
-    libze1
-
-# required by pytorch / ipex
-RUN apt-get install -y --no-install-recommends --fix-missing \
+    git \
+    libgomp1 \
+    libtbb12 \
     libgl1 \
-    libglib2.0-0 \
-    libgomp1
+    libglib2.0-0
+
+# NPU driver
+RUN wget https://github.com/intel/linux-npu-driver/releases/download/v1.28.0/linux-npu-driver-v1.28.0.20251218-20347000698-ubuntu2404.tar.gz &&\
+    tar -xf linux-npu-driver-v1.28.0.20251218-20347000698-ubuntu2404.tar.gz &&\
+    dpkg -i *.deb &&\
+    rm -f linux-npu-driver-*.tar.gz intel-*
 
 # python3.12
 RUN apt-get install -y --no-install-recommends --fix-missing \
@@ -49,50 +43,43 @@ RUN apt-get install -y --no-install-recommends --fix-missing \
     python3-venv \
     python3-pip
 
-# jemalloc is not required but it is highly recommended (also used with optional ipexrun)
-RUN apt-get install -y --no-install-recommends --fix-missing libjemalloc-dev
-ENV LD_PRELOAD=libjemalloc.so.2
+# intel compute runtime
+RUN add-apt-repository ppa:kobuk-team/intel-graphics
+RUN apt-get update
+
+RUN apt-get install -y --no-install-recommends --fix-missing \
+    intel-opencl-icd \
+    libze-intel-gpu1 \
+    libze1
 
 # cleanup
 RUN /usr/sbin/ldconfig
 RUN apt-get clean && rm -rf /var/lib/apt/lists/*
 
-# stop pip and uv from caching
-ENV PIP_NO_CACHE_DIR=true
-ENV UV_NO_CACHE=true
-
 # set paths to use with sdnext
 ENV SD_DOCKER=true
+ENV SD_VAE_DEBUG=true
 ENV SD_DATADIR="/mnt/data"
 ENV SD_MODELSDIR="/mnt/models"
 ENV venv_dir="/mnt/python/venv"
-
-# paths used by sdnext can be a volume if necessary
-#VOLUME [ "/app" ]
-#VOLUME [ "/mnt/data" ]
-#VOLUME [ "/mnt/models" ]
-#VOLUME [ "/mnt/python" ]
-#VOLUME [ "/root/.cache/huggingface" ]
-
-# intel specific environment variables
-#ENV IPEX_SDPA_SLICE_TRIGGER_RATE=1
-#ENV IPEX_ATTENTION_SLICE_RATE=0.5
-#ENV IPEX_FORCE_ATTENTION_SLICE=-1
-#ENV IPEXRUN=False
+ENV IPEX_SDPA_SLICE_TRIGGER_RATE=1
+ENV IPEX_ATTENTION_SLICE_RATE=0.5
+ENV IPEX_FORCE_ATTENTION_SLICE=1
+ENV IPEXRUN=True
 
 # git clone and run sdnext
-RUN echo '#!/bin/bash\ngit status || git clone https://github.com/vladmandic/sdnext.git .\n/app/webui.sh "$@"' | tee /bin/startup.sh
+RUN echo '#!/bin/bash\ngit status || git clone https://github.com/liutyi/sdnext.git -b pytorch .\n/app/webui.sh "$@"' | tee /bin/startup.sh
 RUN chmod 755 /bin/startup.sh
 
 # actually run sdnext
 WORKDIR /app
-ENTRYPOINT [ "startup.sh", "-f", "--use-ipex", "--uv", "--listen", "--debug", "--api-log", "--log", "sdnext.log" ]
+ENTRYPOINT [ "startup.sh", "-f", "--use-ipex", "--uv", "--listen", "--insecure", "--api-log", "--log", "sdnext.log" ]
 
 # expose port
 EXPOSE 7860
 
 # healthcheck function
-# HEALTHCHECK --interval=60s --timeout=10s --start-period=60s --retries=3 CMD curl --fail http://localhost:7860/sdapi/v1/status || exit 1
+#HEALTHCHECK --interval=60s --timeout=10s --start-period=60s --retries=3 CMD curl --fail http://localhost:7860/sdapi/v1/status || exit 1
 
 # stop signal
 STOPSIGNAL SIGINT
